export const robots=[
  {
    id:1,
    name:'number1',
    username:'number1',
    email:'number1@gmail.com'
  },
  {
    id:2,
    name:'number2',
    username:'number2',
    email:'number2@gmail.com'
  },
  {
    id:3,
    name:'number3',
    username:'number3',
    email:'number3@gmail.com'
  },
  {
    id:4,
    name:'number4',
    username:'number4',
    email:'number4@gmail.com'
  },
  {
    id:5,
    name:'number5',
    username:'number5',
    email:'number5@gmail.com'
  },
  {
    id:6,
    name:'number6',
    username:'number6',
    email:'number6@gmail.com'
  },
]